name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code and Define Variables
        uses: actions/checkout@v2

      - name: Set Terraform Variables
        run: |
          cd Terraform
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          terraform init
        shell: bash

      - name: Archive Repository
        run: |
          zip -r my-repo-artifact.zip .
        working-directory: ./

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-repo-artifact
          path: my-repo-artifact.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-repo-artifact

      - name: Unzip Artifact
        run: |
          cd /home/runner/work/TCRC-Backend/TCRC-Backend
          unzip -o my-repo-artifact.zip -d .
        shell: bash

      - name: Use Build Outputs
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Backend
        run: |
          cd Terraform
          terraform apply -auto-approve
        shell: bash

  destroy:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-repo-artifact

      - name: Unzip Artifact
        run: |
          cd /home/runner/work/TCRC-Backend/TCRC-Backend
          unzip -o my-repo-artifact.zip -d .
        shell: bash

      - name: Manual Destruction Confirmation
        run: |
          cd Terraform
          terraform destroy -auto-approve
        shell: bash
