name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code and Define Variables
        uses: actions/checkout@v2

      - name: Set Terraform Variables
        run: |
          cd Terraform
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          terraform init
        shell: bash

      - name: Archive Repository
        run: |
          zip -r my-repo-artifact.zip .
        working-directory: ./

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-repo-artifact
          path: my-repo-artifact.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Use Build Outputs
        uses: actions/download-artifact@v2
        with:
          name: my-repo-artifact

      - name: Deploy Backend
        run: |
          cd /home/runner/work/TCRC-Backend/TCRC-Backend
          ls
          # terraform apply -auto-approve
        shell: bash

  destroy:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Manual Destruction Confirmation
        run: |
          echo "Are you sure you want to destroy your infrastructure?"
          read -p "Type 'yes' to confirm: " confirmation
          if [ "$confirmation" == "yes" ]; then
            echo "Confirmed. Initiating destruction."
            cd Terraform
            terraform destroy -auto-approve
          else
            echo "Not confirmed. Skipping destruction."
          fi
        shell: bash
